### ISSUE TITLE
send http header user agent

### ISSUE THREAD

**Issue by isimluk** [rolieup/golie#25]
Sending over full golie version is preferable.

This may one day turn out to be beneficial for some IT/ops guys trying to analyze their traffic.

**Comment by isimluk** [comment]
As a pre-requisite, this project will need to have formal version string. That version string shall be re-usable by standard `go.mod` machinery (semantic versioning) and thus it is preferable to prefix the version with `v0.`.

**Comment by carlosmmatos** [comment]
so start with v0.1.0 to begin the process of tagging releases rolling?

**Comment by isimluk** [comment]
Sounds good! :+1:

**Comment by carlosmmatos** [comment]
> As a pre-requisite, this project will need to have formal version string. That version string shall be re-usable by standard `go.mod` machinery (semantic versioning) and thus it is preferable to prefix the version with `v0.`.

New tag has been created. Going to work on implementing the sending of the version over HTTP header
